### ISSUE TITLE
nothing displayed in the modeline

### ISSUE THREAD

**Issue by NapoleonWils0n** [elken/doom-modeline-now-playing#4]
Hi Mate

i have doom-modeline-now-playing installed with melpa
and the following code in my my intel.el

but nothing is displayed in the modeline when a video is playing with mpv
i have playerctl and mpv-mpris installed

running M-x doom-modeline-now-playing-toggle-status 
toggles playing and pausing a video playing with mpv 

im using emacs 30
i also tried using the mode-line-misc-info and global-mode-string but that didnt work either

am i missing something obvious
i coulnt find anything online about this project apart from the github page

i made a little script using playerctl and dunst to display info about the currently playing video
but im using emacs ednc for my notifications now

so this project is right up my street i just cant figure out why nothing is showing up in the modeline

Desktop notifications for Youtube and other video sites and players with playerctl
https://www.youtube.com/watch?v=pJrIoIHCQ-0

`;; doom modeline now playing
(require 'doom-modeline-now-playing)
(doom-modeline-now-playing-timer)

;; Define your custom doom-modeline
(doom-modeline-def-modeline 'main
  '(bar matches buffer-info remote-host buffer-position parrot selection-info)
  '(now-playing misc-info minor-modes input-method buffer-encoding major-mode process vcs check time))
`

**Comment by elken** [comment]
There's not a lot I can action from here. Check `*Messages*` for anything relevant

**Comment by NapoleonWils0n** [comment]
cheers, ill dig around and see if i can find anything
maybe an issue with emacs 30

**Comment by elken** [comment]
I don't use it so maybe. If there's nothing obvious I'll probably close this as a `master` bug since you should only be running it if you're happy fixing issues on your own.

**Comment by NapoleonWils0n** [comment]
i found the error in message

Error during redisplay: (eval (doom-modeline-segment--now-playing) t) signaled (error "Unable to find icon with name ‘music’ in icon set ‘faicon’") [94 times]

**Comment by elken** [comment]
Ah I forgot they moved to nerd-icons now, okay this is actually a bug and I'll get a fix up today sometime. Thanks for reporting :)

**Comment by NapoleonWils0n** [comment]
yes doom modeline changed from all the icons to nerd icons a while ago

**Comment by NapoleonWils0n** [comment]
hi mate, i managed to get the icons working

i copied the code from doom-modeline-now-playing.el
and stuck it in my init.el

i used this page to find the names of the icons

https://www.nerdfonts.com/cheat-sheet

i prefixed the icon names with nf-fa-

eg changed 

spotify

to

nf-fa-spotify

i have tested opening a local video with dired and the icons show up
and i also tested a youtube video with elfeed and the icons work as well


(doom-modeline-def-segment now-playing
  "Current status of playerctl. Configurable via
variables for update interval, output format, etc."
  (when (and doom-modeline-now-playing
             (doom-modeline--active)
             doom-modeline-now-playing-status
             (not (string= (now-playing-status-player doom-modeline-now-playing-status) "No players found")))
    (let ((player (now-playing-status-player doom-modeline-now-playing-status))
          (status (now-playing-status-status doom-modeline-now-playing-status))
          (text   (now-playing-status-text   doom-modeline-now-playing-status)))
      (concat
       (doom-modeline-spc)
       (if (string= "spotify" player)
           (doom-modeline-icon 'faicon "nf-fa-spotify" "" "#"
                               :face 'doom-modeline-now-playing-icon
                               :v-adjust -0.0575)
         (doom-modeline-icon 'faicon "nf-fa-music" "" "#"
                             :face 'doom-modeline-now-playing-icon
                             :v-adjust -0.0575))
       (doom-modeline-spc)
       (propertize (if (equal status "playing")
                       (doom-modeline-icon 'faicon "nf-fa-play" "" ">"
                                           :v-adjust -0.0575)
                     (doom-modeline-icon 'faicon "nf-fa-pause" "" "||"
                                         :v-adjust -0.0575))
                   'mouse-face 'mode-line-highlight
                   'help-echo "mouse-1: Toggle player status"
                   'local-map (let ((map (make-sparse-keymap)))
                                (define-key map [mode-line mouse-1] 'doom-modeline-now-playing-toggle-status)
                                map))
       (doom-modeline-spc)
       (propertize
        (truncate-string-to-width text doom-modeline-now-playing-max-length nil nil "...")
        'face 'doom-modeline-now-playing-text)))))

**Comment by elken** [comment]
Yeah I know the fix, I just need to do it :)

**Comment by NapoleonWils0n** [comment]
hope you dont mind a bit of feedback mate
and a feature request

i changed the max length to 100
set the interval to 1and set the position and duration with the playerctl code

that gives a really nice layout with the position thats updated in real time and the duration

the doom-modeline-now-playing-max-length obviously determines the full length of the modeline

feature request 

what would be really great is if its possible to truncate the title
because if its a long title and you place the position and duration after the title they get cut off and arent displayed

i had the same issue with playerctl in a script and used awk to trim the title

the other minor thing is how to not display the music icon 
and only the play/pause icon

`
;; max length
(setq doom-modeline-now-playing-max-length 100)

;; update
(setq doom-modeline-now-playing-interval 1)

;; format
(setq doom-modeline-now-playing-format "{{title}} - [{{duration(position)}}/{{duration(mpris:length)}}]")

`

screenshot of emacs playing Dynasty (my secret shame)

![20240522_15h18m20s_grim](https://github.com/elken/doom-modeline-now-playing/assets/2666091/f3f0e6df-3fc5-4023-b910-213475006b5d)

**Comment by elken** [comment]
It is possible to truncate it, set the max length lower. And don't pollute issues.
